// <auto-generated />
using FairAI.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FairAI.Api.Migrations
{
    [DbContext(typeof(FairAiDbContext))]
    [Migration("20261010113209_modelfix4")]
    partial class modelfix4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FairAI.Api.Domain.CoreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Position")
                        .HasColumnType("double");

                    b.Property<double>("Range")
                        .HasColumnType("double");

                    b.Property<double>("Speed")
                        .HasColumnType("double");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("coreset", (string)null);
                });

            modelBuilder.Entity("FairAI.Api.Domain.NeuronModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("neuronset", (string)null);
                });

            modelBuilder.Entity("FairAI.Api.Domain.TextModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("LanguageValue")
                        .HasColumnType("double");

                    b.Property<string>("LastWord")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("MeaningValue")
                        .HasColumnType("double");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("dataset", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
